"""empty message

Revision ID: 2d8fdb78f5ba
Revises: bfde2815aef9
Create Date: 2024-08-19 01:02:43.742321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2d8fdb78f5ba'
down_revision: Union[str, None] = 'bfde2815aef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignmsent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignmsent',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('anio_academico', sa.VARCHAR(), nullable=False),
    sa.Column('asignatura', sa.VARCHAR(), nullable=False),
    sa.Column('paralelo', sa.VARCHAR(), nullable=False),
    sa.Column('trimestre', sa.VARCHAR(), nullable=False),
    sa.Column('actividades_tipo', sa.VARCHAR(), nullable=False),
    sa.Column('actividades_asignacion', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
