"""empty message

Revision ID: bfde2815aef9
Revises: 277cad49d2b0
Create Date: 2024-08-16 07:06:57.474125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bfde2815aef9'
down_revision: Union[str, None] = '277cad49d2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignmsent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio_academico', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asignatura', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paralelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trimestre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actividades_tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actividades_asignacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('assignmsent')
    # ### end Alembic commands ###
